package:
  name: jpy
  version: "0.9.0"

source:
  url: https://github.com/bcdev/jpy/archive/0.9.0.zip
  md5: e9690ff15874c7eefde2979c57926da4
  #path: ../jpy

build:
  
  entry_points:

  number: 2

requirements:
  build:
    - python
    - setuptools
    - java-1.7.0-openjdk-cos6-x86_64=1.7.0.131

  run:
    - python

test:
  imports:

  commands:

about:
  home: https://github.com/bcdev/jpy.git
  license: GPL v3
  summary: "jpy is a bi-directional Python-Java bridge which you can use to embed Java code in Python programs or the other way round"


