package:
  name: jpy
  version: "0.7.5"

source:
  path: ../jpy

build:
  
  entry_points:

  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:

  commands:

about:
  home: https://github.com/bcdev/jpy.git
  license: GPL v3
  summary: "jpy is a bi-directional Python-Java bridge which you can use to embed Java code in Python programs or the other way round"


